site_name: AdvancedDevSample Documentation
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Architecture: diagrams/architecture.md
  - Class Diagrams: diagrams/class_diagram.md
  - Sequence Diagrams: diagrams/sequence_diagram.md
  - Component Diagrams: diagrams/component_diagram.md
  - Flow Diagrams: diagrams/flow_diagram.md
  - API Reference: api_docs.md
