site_name: AdvancedDevSample Documentation
theme:
  name: material
  language: fr

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Accueil: index.md
  - Guide du Développeur: developer_guide.md
  - Architecture: diagrams/architecture.md
  - Diagrammes de Classes: diagrams/class_diagram.md
  - Diagrammes de Séquence: diagrams/sequence_diagram.md
  - Diagrammes de Composants: diagrams/component_diagram.md
  - Diagrammes de Flux: diagrams/flow_diagram.md
  - Référence API: api_docs.md
